from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from datetime import datetime

def generate_pdf(result):

    file_path = "reports/security_report.pdf"
    doc = SimpleDocTemplate(file_path, pagesize=A4)

    styles = getSampleStyleSheet()
    content = []

    # -------------------------
    # TITLE PAGE
    # -------------------------
    title = Paragraph("<b>CyberSentinel Security Assessment Report</b>", styles["Title"])
    subtitle = Paragraph("Automated Cyber Risk Analysis Report", styles["Normal"])
    date = Paragraph(f"Generated on: {datetime.now()}", styles["Normal"])

    content += [title, Spacer(1, 10), subtitle, Spacer(1, 10), date, Spacer(1, 20)]

    content.append(PageBreak())

    # -------------------------
    # TARGET INFO
    # -------------------------
    content.append(Paragraph("<b>1. Target Information</b>", styles["Heading2"]))

    target_data = [
        ["URL", result.get("url", "")],
        ["Domain", result.get("domain", "")],
        ["IP Address", result.get("ip", "")],
        ["HTTP Status", str(result.get("http_status", ""))],
        ["SSL Enabled", str(result.get("ssl", ""))]
    ]

    table = Table(target_data)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.grey),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
        ("BACKGROUND", (0, 1), (-1, -1), colors.lightgrey),
    ]))

    content += [table, Spacer(1, 20)]

    # -------------------------
    # RISK SUMMARY
    # -------------------------
    content.append(Paragraph("<b>2. Risk Summary</b>", styles["Heading2"]))

    risk_data = [
        ["Risk Score", str(result.get("risk_score", ""))],
        ["Risk Level", result.get("risk_level", "")],
        ["Final Verdict", result.get("safety_verdict", "")]
    ]

    risk_table = Table(risk_data)
    risk_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
        ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
    ]))

    content += [risk_table, Spacer(1, 20)]

    # -------------------------
    # ISSUES SECTION
    # -------------------------
    content.append(Paragraph("<b>3. Security Issues</b>", styles["Heading2"]))

    issues = result.get("issues", [])

    if issues:
        issue_table_data = [["Issue", "CVSS", "Severity"]]

        for issue in issues:
            issue_table_data.append([
                issue.get("name", ""),
                str(issue.get("cvss_score", "")),
                issue.get("severity", "")
            ])

        issue_table = Table(issue_table_data)

        issue_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.darkred),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
            ("BACKGROUND", (0, 1), (-1, -1), colors.lightgrey),
        ]))

        content.append(issue_table)
    else:
        content.append(Paragraph("No major issues detected.", styles["Normal"]))

    content.append(Spacer(1, 20))

    # -------------------------
    # FOOTER NOTE
    # -------------------------
    footer = Paragraph(
        "<i>This report is automatically generated by CyberSentinel AI Security Engine.</i>",
        styles["Normal"]
    )

    content.append(footer)

    # -------------------------
    # BUILD PDF
    # -------------------------
    doc.build(content)