from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from datetime import datetime
import os

def generate_pdf(data):

    os.makedirs("reports", exist_ok=True)

    file_path = "reports/security_report.pdf"
    doc = SimpleDocTemplate(file_path)

    styles = getSampleStyleSheet()
    content = []

    # ======================
    # TITLE
    # ======================
    title = Paragraph(
        "<b><font size=18>Cyber Sentinel Security Report</font></b>",
        styles["Title"]
    )
    content.append(title)
    content.append(Spacer(1, 12))

    # ======================
    # BASIC INFO
    # ======================
    info = [
        ["Target URL", data["url"]],
        ["Domain", data["domain"]],
        ["IP Address", data["ip"]],
        ["HTTP Status", str(data["http_status"])],
        ["Scan Time", datetime.now().strftime("%Y-%m-%d %H:%M:%S")],
    ]

    table = Table(info)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.grey),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.black),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))

    content.append(table)
    content.append(Spacer(1, 15))

    # ======================
    # RISK SECTION
    # ======================
    score = data["risk_score"]
    verdict = data["safety_verdict"]

    risk_color = colors.green
    if score < 50:
        risk_color = colors.red
    elif score < 80:
        risk_color = colors.orange

    risk_table = Table([
        ["Risk Score", f"{score}/100"],
        ["Safety Verdict", verdict],
        ["Summary", data["final_summary"]]
    ])

    risk_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), risk_color),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))

    content.append(risk_table)
    content.append(Spacer(1, 15))

    # ======================
    # SECURITY HEADERS
    # ======================
    content.append(Paragraph("<b>Security Headers Analysis</b>", styles["Heading2"]))

    headers = data.get("headers", {})
    for k, v in headers.items():
        content.append(Paragraph(f"<b>{k}:</b> {v}", styles["Normal"]))

    content.append(Spacer(1, 15))

    # ======================
    # ISSUES
    # ======================
    content.append(Paragraph("<b>Detected Issues</b>", styles["Heading2"]))

    if data["issues"]:
        for issue in data["issues"]:
            content.append(Paragraph(f"• {issue['name']}", styles["Normal"]))
            content.append(Paragraph(
                f"Risk: {issue['explanation']['risk']}",
                styles["Normal"]
            ))
            content.append(Spacer(1, 6))
    else:
        content.append(Paragraph("No major issues detected.", styles["Normal"]))

    # ======================
    # FOOTER
    # ======================
    content.append(Spacer(1, 20))
    content.append(Paragraph(
        "Generated by Cyber Sentinel AI Security Engine",
        styles["Italic"]
    ))

    doc.build(content)

    return file_path