from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from datetime import datetime

def generate_pdf(result):

    doc = SimpleDocTemplate(
        "reports/security_report.pdf",
        pagesize=A4,
        rightMargin=30,
        leftMargin=30,
        topMargin=30,
        bottomMargin=30
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "title",
        parent=styles["Title"],
        fontSize=24,
        textColor=colors.HexColor("#0B2E4A"),
        alignment=1,
        spaceAfter=20
    )

    header_style = ParagraphStyle(
        "header",
        parent=styles["Heading2"],
        fontSize=14,
        textColor=colors.HexColor("#111827"),
        spaceAfter=10
    )

    normal = styles["Normal"]

    content = []

    # =========================
    # COVER PAGE
    # =========================
    content.append(Paragraph("CYBERSENTINEL SOC SECURITY REPORT", title_style))

    content.append(Spacer(1, 10))

    content.append(Paragraph(
        "<b>Type:</b> Automated Vulnerability & Risk Assessment",
        normal
    ))

    content.append(Paragraph(
        f"<b>Date:</b> {datetime.now()}",
        normal
    ))

    content.append(Paragraph(
        f"<b>Target:</b> {result.get('url','')}",
        normal
    ))

    content.append(PageBreak())

    # =========================
    # EXECUTIVE SUMMARY
    # =========================
    content.append(Paragraph("1. Executive Summary", header_style))

    summary_box = f"""
    <b>Final Verdict:</b> {result.get('safety_verdict','')}<br/>
    <b>Risk Score:</b> {result.get('risk_score',0)}/100<br/>
    <b>Risk Level:</b> {result.get('risk_level','')}<br/><br/>

    <b>Summary:</b><br/>
    {result.get('final_summary','')}
    """

    table = Table([[Paragraph(summary_box, normal)]])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,-1), colors.HexColor("#F3F4F6")),
        ("BOX", (0,0), (-1,-1), 1, colors.HexColor("#9CA3AF")),
        ("PADDING", (0,0), (-1,-1), 12),
    ]))

    content.append(table)
    content.append(Spacer(1, 15))

    # =========================
    # TARGET INFORMATION
    # =========================
    content.append(Paragraph("2. Target Information", header_style))

    target_data = [
        ["URL", result.get("url","")],
        ["Domain", result.get("domain","")],
        ["IP Address", result.get("ip","")],
        ["HTTP Status", str(result.get("http_status",""))],
        ["SSL Enabled", str(result.get("ssl",""))],
    ]

    t = Table(target_data)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#1F2937")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("GRID", (0,0), (-1,-1), 0.5, colors.black),
        ("BACKGROUND", (0,1), (-1,-1), colors.whitesmoke),
        ("PADDING", (0,0), (-1,-1), 6),
    ]))

    content.append(t)
    content.append(Spacer(1, 15))

    # =========================
    # VULNERABILITY ASSESSMENT
    # =========================
    content.append(Paragraph("3. Vulnerability Assessment", header_style))

    issues = result.get("issues", [])

    if issues:

        data = [["Vulnerability", "CVSS", "Severity"]]

        for i in issues:
            severity = i.get("severity","LOW")

            data.append([
                i.get("name",""),
                str(i.get("cvss_score","")),
                severity
            ])

        vt = Table(data)

        vt.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#DC2626")),
            ("TEXTCOLOR", (0,0), (-1,0), colors.white),
            ("GRID", (0,0), (-1,-1), 0.5, colors.black),
            ("BACKGROUND", (0,1), (-1,-1), colors.HexColor("#F9FAFB")),
            ("PADDING", (0,0), (-1,-1), 6),
        ]))

        content.append(vt)

    else:
        content.append(Paragraph("No vulnerabilities detected.", normal))

    content.append(Spacer(1, 20))

    # =========================
    # SECURITY CONCLUSION
    # =========================
    content.append(Paragraph("4. Security Conclusion", header_style))

    conclusion = f"""
    <b>Status:</b> {result.get('safety_verdict','')}<br/><br/>

    <b>Interpretation:</b><br/>
    SAFE → Secure system<br/>
    MODERATE → Improvements required<br/>
    HIGH RISK → Immediate remediation required<br/><br/>

    <b>Final Assessment:</b><br/>
    {result.get('final_summary','')}
    """

    content.append(Paragraph(conclusion, normal))

    # =========================
    # FOOTER
    # =========================
    content.append(Spacer(1, 20))
    content.append(Paragraph(
        "<i>Confidential SOC Report - Generated by CyberSentinel Security Engine</i>",
        normal
    ))

    doc.build(content)